name: Core enhancement issues
description: 画面の本実装課題を作成する
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: program-design
    attributes:
      label: 設計
      description: 設計がない場合、以下の行を実装する内容の説明に置き換える
      value: '- [設計](ここに設計スライドのパス)'
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: ToDo
      description: やることリスト、不要な項目は削除し、必要な項目は追加する
      value: |-
        - [ ] 画面レイアウト
        - [ ] バリデ
        - [ ] API 結合
        - [ ] API 結合動作確認
        - [ ] ページ遷移制御確認
        - [ ] 必要に応じて Context など必要な内容が引き継がれていること
    validations:
      required: true
